### ISSUE TITLE
can u help me

### ISSUE THREAD

**Issue by Xeto2W** [tizxr/Beam-On-Join#2]
can u help me whit it

**Comment by ghost** [comment]
its scareware, and a poorly implemented one too. Why even bother?

**Comment by n6icko** [comment]
> its scareware, and a poorly implemented one too. Why even bother?

yo bro do you know how to change a manifest to v3?

**Comment by ghost** [comment]
> > its scareware, and a poorly implemented one too. Why even bother?
> 
> yo bro do you know how to change a manifest to v3?

what?

**Comment by tizxr** [comment]
@Nexuzzzz Yea well its made pretty poorly made but its pretty easy to setup.

**Comment by tizxr** [comment]
> can u help me whit it
Its simple, go to discord  portal, make a discord bot. Go to the bot page, enable member intents and copy the bot token. Go to the last line of the code and put your bot token in the string. Then invite the bot to your server and make a channel. Copy the channel ID and put it in the logging channel. Then install all the imports and then run the file either on ur PC or on replit and pretty much then its done!
